### ISSUE TITLE
nopickup function not working anymore

### ISSUE THREAD

**Issue by 7934345** [Kyromyr/D2Stats#17]
version D2Stats-3.11.1 works well
but D2Stats-3.11.3 stop working

**Comment by 7934345** [comment]
by the way how to "hide magic sacred"? I have googled and search the forums, but find no clue.

**Comment by Kyromyr** [comment]
It's working for me on 3.11.3.

"hide magic sacred" should work fine. If you need help with the notifier, the discord server should be the best place to ask.
